version: "3.9"
services:
  db:
    image: enthusiast17/nodejs2021q4-service_db:latest
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT_PUBLIC: ${POSTGRES_PORT_PUBLIC}
      POSTGRES_PORT: ${POSTGRES_PORT}
    env_file:
      - .env.docker
    ports:
      - ${POSTGRES_PORT_PUBLIC}:${POSTGRES_PORT}
    volumes:
      - /postgres:/var/lib/postgresql/data
    networks:
      - net
  app:
    image: enthusiast17/nodejs2021q4-service_app:latest
    restart: on-failure
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.app
    env_file:
      - .env.docker
    ports:
      - ${PORT}:${PORT}
    volumes:
      - /logs:/node/logs
    links:
      - db
    networks:
      - net
networks:
  net:
    name: user-bridge-net
    driver: bridge
    external: true
