version: "3.9"
services:
  db:
    image: enthusiast17/nodejs2021q4-service_db:latest
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT_PROD}
    volumes:
      - /postgres:/var/lib/postgresql/data
    networks:
      - net
  app:
    image: enthusiast17/nodejs2021q4-service_app:latest
    restart: on-failure
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - ${PORT}:${PORT_PROD}
    volumes:
      - /logs:/node/logs
    networks:
      - net
networks:
  net:
    name: user-bridge-net
    driver: bridge
